on:
  push:
    branches:
    - master
  pull_request:

name: Run Tox tests

jobs:
  tox_test:
    name: Tox test
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        # N.B. Keep the env list in sync with tox.ini
        tox_env: [
            py27-c90,
            py27-c99, py37-c99, py38-c99, py39-c99, py310-c99, py311-c99,
            py27-cpp14, py37-cpp17, py38-cpp17, py39-cpp17, py310-cpp17, py311-c99,
        ]

      # Old Python versions tend to have their own problems, so the CI
      # isn't green all the time :(
      # With this flag, GHA will show all issues so they can be analyzed.
      fail-fast: false

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest

  py33-test:
    name: Python 3.3 test
    container: python:3.3
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        CFLAGS: "-Werror -Wall -Wno-error=strict-aliasing"
      run: |
        CFLAGS="$CFLAGS -std=c90" make test-python
        CFLAGS="$CFLAGS -std=c99" make test-python
        make test-python-cpp

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest

  py34-test:
    name: Python 3.4 test
    container: python:3.4
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        CFLAGS: "-Werror -Wall -Wno-error=strict-aliasing"
      run: |
        CFLAGS="$CFLAGS -std=c90" make test-python
        CFLAGS="$CFLAGS -std=c99" make test-python
        CFLAGS="$CFLAGS -std=c++14" make test-python-cpp

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest

  py35-test:
    name: Python 3.5 test
    container: python:3.5
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        CFLAGS: "-Werror -Wall -Wno-error=strict-aliasing"
      run: |
        CFLAGS="$CFLAGS -std=c90" make test-python
        CFLAGS="$CFLAGS -std=c99" make test-python
        CFLAGS="$CFLAGS -std=c++14" make test-python-cpp

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest

  py36-test:
    name: Python 3.6 test
    container: python:3.6
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        CFLAGS: "-Werror -Wall -Wno-error=strict-aliasing"
      run: |
        CFLAGS="$CFLAGS -std=c90" make test-python
        CFLAGS="$CFLAGS -std=c99" make test-python
        CFLAGS="$CFLAGS -std=c++14" make test-python-cpp

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
